/**
 * @file Notification.cpp
 * @brief Notification persistence and network-view helpers implementation.
 *
 * Implements the lightweight notification service used to store and retrieve
 * user-facing messages generated by offer workflows.
 * @author Aaron Shuan Xie (axie46)
 */

#include "Notification.h"
#include "Database.h"

#include <string>

using namespace std;

bool Notification::add(int user_id, const string& message) {
    // Simple append-only notification insert.
    sqlite3* db = Database::open();  // Database handle used for the insert.
    if (!db) return false;

    sqlite3_stmt* stmt = nullptr;  // Prepared statement for inserting one notification row.
    // Prepare the insert once, then bind the notification recipient and message body.
    if (sqlite3_prepare_v2(db, "INSERT INTO notifications (user_id, message) VALUES (?, ?);", -1, &stmt,
                           nullptr) != SQLITE_OK) {
        Database::close(db);
        return false;
    }
    sqlite3_bind_int(stmt, 1, user_id);
    sqlite3_bind_text(stmt, 2, message.c_str(), -1, SQLITE_TRANSIENT);
    // SQLITE_DONE means the row was appended successfully.
    bool ok = (sqlite3_step(stmt) == SQLITE_DONE);  // True when the notification insert completed successfully.
    sqlite3_finalize(stmt);
    // Close the short-lived DB connection before returning the success flag.
    Database::close(db);
    return ok;
}

Notification::ViewData Notification::view(int user_id) {
    // Return typed notification payload; API shaping belongs to ResponseBuilder.
    sqlite3* db = Database::open();  // Database handle used for loading the user's notification feed.
    if (!db) return {false, "DB Error", {}};

    sqlite3_stmt* stmt = nullptr;  // Prepared statement for selecting notification messages.
    if (sqlite3_prepare_v2(db,
                           "SELECT message FROM notifications WHERE user_id=? ORDER BY notification_id DESC;", -1,
                           &stmt, nullptr) != SQLITE_OK) {
        Database::close(db);
        return {false, "DB Error", {}};
    }
    // Restrict the query to one user's notifications in newest-first order.
    sqlite3_bind_int(stmt, 1, user_id);

    vector<string> notes;  // Accumulates notification messages in newest-first order.
    // Copy each notification message into the typed response vector.
    while (sqlite3_step(stmt) == SQLITE_ROW) {
        const unsigned char* text = sqlite3_column_text(stmt, 0);
        notes.push_back(text ? reinterpret_cast<const char*>(text) : "");
    }
    sqlite3_finalize(stmt);
    // Return the accumulated messages to the API layer.
    Database::close(db);
    return {true, "OK", notes};
}
