// Notification.h
// MustangMarketplace — Group 49
// Stories 8, 9

#ifndef NOTIFICATION_H
#define NOTIFICATION_H

#include <string>
#include <vector>

/**
 * @file Notification.h
 * @brief Notification persistence and network-view helpers.
 *
 * Declares the lightweight notification service used to store and retrieve
 * user-facing messages generated by offer workflows.
 * @author Aaron Shuan Xie (axie46)
 */

/**
 * @class Notification
 * @brief Notification service methods.
 *
 * Provides persistence and retrieval helpers for notification messages that
 * are later returned to the client in typed form.
 * @author Aaron Shuan Xie (axie46)
 */
class Notification {
public:
    /**
     * @struct ViewData
     * @brief Typed notification-view payload consumed by ResponseBuilder.
     * @author Aaron Shuan Xie (axie46)
     *
     * Carries a success flag, a user-facing message, and the ordered
     * notification lines returned by the view operation.
     */
    struct ViewData {
        /** True when the notification query completed successfully. */
        bool ok = false;
        /** User-facing status message for the notification request. */
        std::string message;
        /** Ordered notification lines returned for the user. */
        std::vector<std::string> notes;
    };

    // Supports Stories 8 and 9: Offer-created and offer-response notifications
    /**
     * @brief Adds a notification message for a user.
     *
     * Persists a single notification line for the target user so it can be
     * surfaced later through the notifications view.
     * @author Aaron Shuan Xie (axie46)
     * @param user_id Destination user id.
     * @param message Notification text.
     * @return True on successful insert.
     */
    static bool add(int user_id, const std::string& message);

    // Supports Stories 8 and 9: Viewing notifications generated by offer flows
    /**
     * @brief Returns typed notifications for a user.
     *
     * Loads notification lines for the requested user and packages them into a
     * typed response structure for downstream response builders.
     * @author Aaron Shuan Xie (axie46)
     * @param user_id Current user id.
     * @return Struct containing status/message and ordered notification lines.
     */
    static ViewData view(int user_id);
};

#endif
